- hosts: all
  become: true
  tasks:
    - apt_repository:
        repo: 'ppa:ondrej/php'
    - apt:
        update_cache: yes
    - apt: name={{item}} state=installed
      with_items:
        - apache2
        - php5.6
        - php5.6-mysql
        - php5.6-cli
        - php5.6-mcrypt
        - php5.6-mbstring
        - php5.6-mysql
        - php5.6-gd
        - php5.6-intl
        - php5.6-curl
        - mysql-server
        - python-mysqldb
    - mysql_db: name=epesi state=present
    - mysql_user:
        name: admin
        password: 1234
        priv: 'epesi.*:ALL,GRANT'
        state: present
